lib/iv_romance_web/router.ex
defmodule IvRomanceWeb.Router do
  use IvRomanceWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(IvRomanceWeb.Plugs.AcceptHeader)
    plug(IvRomance.Admin.Auth.Plug, source: :auth_header)
  end

  pipeline :auth do
    plug(:put_layout, {IvRomanceWeb.LayoutView, :auth})
  end

  pipeline :admin do
    plug(:put_layout, {IvRomanceWeb.LayoutView, :admin})
    plug(IvRomance.Admin.Auth.Plug)
  end

  scope "/admin", IvRomanceWeb.Admin, as: :admin do
    pipe_through([:browser, :auth])
    resources("/sessions", SessionController, only: [:new, :create, :delete])
  end

  scope "/admin", IvRomanceWeb.Admin, as: :admin do
    pipe_through([:browser, :admin, :authenticate_user])
    get("/", PageController, :index, as: :root)
    resources("/pages", PageController, except: [:show])
    resources("/uploads", UploadController, only: [:index, :create, :delete])

    resources("/galleries", GalleryController, except: [:show]) do
      resources("/images", ImageController, only: [:index])
    end

    resources("/media", MediaObjectController, except: [:show])
  end

  scope "/api/admin", IvRomanceWeb.Admin, as: :api_admin do
    pipe_through([:api, :authenticate_user])

    resources("/galleries", GalleryController, only: []) do
      resources("/images", ImageController, only: [:index, :create, :delete])
    end
  end

  scope "/", IvRomanceWeb do
    pipe_through(:browser)

    resources("/photo", GalleryController, only: [:index, :show])
    resources("/media", MediaObjectController, only: [:index])

    get("/*path", PageController, :show)
  end
end

lib/iv_romance_web/views/layout_view.ex
defmodule IvRomanceWeb.LayoutView do
  use IvRomanceWeb, :view

  @tracking_id Application.get_env(:iv_romance, :google_analytics)[:tracking_id]

  def title(%{assigns: %{title: title}}), do: title
  def title(_conn), do: gettext("Ivanovo Club of Romance Music «By the Candlelight»")

  def copyright_timestamp, do: "2005–" <> current_year()

  def tracking_id, do: @tracking_id

  def has_tracking_id?, do: is_binary(tracking_id()) && tracking_id() != ""

  defp current_year do
    DateTime.utc_now()
    |> Map.fetch!(:year)
    |> Integer.to_string()
  end
end

lib/iv_romance_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Admin Panel</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin.css") %>">
  </head>

  <body>
    <div class="wrapper">
      <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
        <div class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="<%= admin_page_path(@conn, :index) %>">Pages</a>
            <a class="navbar-item" href="<%= admin_upload_path(@conn, :index) %>">Uploads</a>
            <a class="navbar-item" href="<%= admin_gallery_path(@conn, :index) %>">Galleries</a>
            <a class="navbar-item" href="<%= admin_media_object_path(@conn, :index) %>">Media</a>
          </div>
          <div class="navbar-end">
            <%= if @current_user do %>
              <%= link "Log out", to: admin_session_path(@conn, :delete, @current_user), class: "navbar-item", method: "delete" %>
            <% end %>
          </div>
        </div>
      </nav>
      <section class="section">
        <%= render @view_module, @view_template, assigns %>
      </section>
    </div>
    <footer class="footer">
      <div class="has-text-centered">
        <p>
          <strong>Footer</strong> and copyrights
        </p>
      </div>
    </footer>
    <script src="<%= static_path(@conn, "/js/admin.js") %>"></script>
  </body>
</html>

lib/iv_romance_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= if has_tracking_id?() do %>
      <script async src="https://www.googletagmanager.com/gtag/js?id=<%= tracking_id() %>"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', '<%= tracking_id() %>');
      </script>
    <% end %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= title(@conn) %></title>

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Cormorant+SC:600" rel="stylesheet">
  </head>

  <body>
    <div class="wrapper">
      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <img
              src="<%= static_path(@conn, "/images/logo.png") %>"
              alt="<%= gettext("Ivanovo Club of Romance Music «By the Candlelight»") %>"
            />
          </a>
          <a class="navbar-item logo is-size-3" href="/"><%= gettext("By the Candlelight") %></a>

          <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div class="navbar-menu" id="navMenu">
          <div class="navbar-start">
            <a class="navbar-item" href="/news"><%= gettext("News") %></a>
            <a class="navbar-item" href="/club"><%= gettext("Club") %></a>
            <a class="navbar-item" href="/articles"><%= gettext("Articles") %></a>
            <a class="navbar-item" href="/participants"><%= gettext("Participants") %></a>
            <a class="navbar-item" href="/concerts"><%= gettext("Concerts") %></a>
            <a class="navbar-item" href="/contact"><%= gettext("Contact") %></a>
            <a class="navbar-item" href="/photo"><%= gettext("Photo") %></a>
            <a class="navbar-item" href="/media"><%= gettext("Media") %></a>
          </div>
        </div>
      </nav>
      <section class="section">
        <div class="container">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </section>
    </div>
    <footer class="footer">
      <div class="has-text-centered">
        <p>
          © <%= copyright_timestamp() %> <%= gettext("Ivanovo Club of Romance Music «By the Candlelight»") %>
        </p>
      </div>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/iv_romance_web/templates/layout/auth.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Admin Panel</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin.css") %>">
  </head>
  <body>
    <section class="section">
      <%= render @view_module, @view_template, assigns %>
    </section>
    <script src="<%= static_path(@conn, "/js/admin.js") %>"></script>
  </body>
</html>